### ISSUE TITLE
Support for SPARQL*

### ISSUE THREAD

**Issue by QuarksToQuasars** [RubenVerborgh/SPARQL.js#105]
Dear Ruben, dear sparql.js community,
 
at [metaphacts](https://github.com/metaphacts) we are excited to see the uptake and standardization efforts of SPARQL*/RDF* within the knowledge graph community. We believe it would be a major step forward for the community to have SPARQL* also properly integrated and supported by the SPARQL.js grammar as one of the main SPARQL parsing and query manipulation libraries.

In 2018 there was already a feature request (see https://github.com/RubenVerborgh/SPARQL.js/issues/65) which was closed due to the immature state of the SPARQL*/RDF* specification and standardization effort. Since the W3C Workshop on Web Standardization for Graph Data in May 2019 in Berlin (https://www.w3.org/Data/events/data-ws-2019/cfp.html) there have been renewed efforts and many graph databases have implemented the proposed standard. Therefore we believe it is time to revisit the topic.
 
Generally, we would be happy to help implement/contribute support for SPARQL* in SPARQL.js. However, we have a few questions:

* Is this of interest to anyone and in particular the project owner?
* Is someone already working on this, i.e. avoid duplication of efforts, join forces and make plans transparent?
* What are the design- and technical prerequisites to get it properly integrated into a sparql.js release? Our current plan would be mainly to extend the parser grammar and serializer along the lines of what has been specified by Olaf Hartig in https://arxiv.org/abs/1406.3399, Section 5 “embedded triple pattern”. As far as we currently look at it, it should be a relatively small and fully compatible extension to the main sparql.js SPARQL 1.1 grammar. Recently, together with Ontotext we implemented a similar extension in RDF4J (c.f. https://github.com/eclipse/rdf4j/issues/1484 and in particular the TripleRef in the JJTree https://github.com/eclipse/rdf4j/pull/1920/commits/251c979f835af8f9f995bca85621df0d144944a2#diff-c4d16e5e970dd365f5811921f25b6a3aR1027)

For those lacking context: An excellent starting point for further reading on SPARQL*/RDF* is this (continuously updated) blog post by Olaf Hartig: https://blog.liu.se/olafhartig/2019/01/10/position-statement-rdf-star-and-sparql-star/ including a list of tools and example SPARQL and RDF parser implementations https://github.com/RDFstar/RDFstarTools .

 
Cheers,
Johannes on behalf of the [metaphacts](https://github.com/metaphacts) Team

**Comment by RubenVerborgh** [comment]
Hi @QuarksToQuasars,

You're coming it at the right moment 🙂

Literally this week, we have been adding RDF* support to N3.js:
- https://github.com/rdfjs/N3.js/pull/210
- https://github.com/rdfjs/N3.js/pull/212

This comes as a result of things moving forward in the RDF/JS group:
- https://github.com/rdfjs/data-model-spec/pull/165

So yes, we're ready now to get this added to SPARQL.js.

I'm checking if @simonvbrae and @rubensworks have the bandwidth for this; in that case, we can even take this up ourselves.

**Comment by QuarksToQuasars** [comment]
Cool. 
> I'm checking if @simonvbrae and @rubensworks have the bandwidth for this; in that case, we can even take this up ourselves.

Let's sync, i.e. we / @AlexeyMz has already started on this to test some implementation ideas (c.f. draft https://github.com/RubenVerborgh/SPARQL.js/pull/106) , so it might be worth that we start from there instead of doing it from scratch.

**Comment by RubenVerborgh** [comment]
Done via #111.
