### ISSUE TITLE
Problem with subqueries in 3.1.0

### ISSUE THREAD

**Issue by joachimvh** [RubenVerborgh/SPARQL.js#116]
This problem occurred when I updated from 3.0.1 to 3.1.0.

The parser now fails on the following query:
```sparql
SELECT ?x WHERE { SELECT ?x ?p ?y WHERE { ?x ?p ?y. } }
```

It works if I add extra braces around the subquery, so
```sparql
SELECT ?x WHERE { { SELECT ?x ?p ?y WHERE { ?x ?p ?y. } } }
```
but this shouldn't be required.

**Comment by RubenVerborgh** [comment]
Added failing test in https://github.com/RubenVerborgh/SPARQL.js/tree/fix/subqueries
