### ISSUE TITLE
Throwing `Projection of ungrouped variable` error on valid query

### ISSUE THREAD

**Issue by LaurensRietveld** [RubenVerborgh/SPARQL.js#120]
We're encountering issues with the most recent sparqljs releases, where the error checking is too strict.
This query is valid, but throws an `Projection of ungrouped variable (?p)` error:

```
select ?p (count(*) as ?n) {
  [ ?p [] ].
}
```

This seems to be introduced by this PR: #108

-----

## Bounty

A [bounty](https://comunica.dev/association/bounties/) has been placed on this issue by:

| |
|-|
| [<img alt="Triply" src="https://nightly.triplydb.com/imgs/logos/logo-lg.svg?v=3" height="25">](https://triply.cc/) |
| €272 |

[Click here to learn more](https://comunica.dev/association/bounty_process/) if you're interested in claiming this bounty by resolving this issue.

**Comment by LaurensRietveld** [comment]
@RubenVerborgh This still seems to be an issue. These two queries fail using the latest version:

**Comment by RubenVerborgh** [comment]
@rubensworks I might need to revert the protection mechanisms that have been built in; it seems that they are not created adequately. This probably will have repercussions on our spec compliance?

**Comment by rubensworks** [comment]
Instead of reverting, perhaps we should instead look into fixing the problem(s) with the protection mechanisms?
It looks to me like reverting would break more things than it would fix.

An alternative would be to add an option to disable the protection mechanisms, which could be used until all (known) issues with it are fixed.

**Comment by RubenVerborgh** [comment]
> Instead of reverting, perhaps we should instead look into fixing the problem(s) with the protection mechanisms?

I will try; it's just the second issue in a very short time. I'm not sure whether they were properly designed.

**Comment by wouterbeek** [comment]
I'm not sure whether this is the same error or a related by different one: when a `group by` clause is used to explicitly specify the grouped-by variables, and a variable appears in the projection but not in an aggregate function, the variable should be sampled (i.e., the equivalent of applying the aggregate function `sample` explicitly).

This means that the following query string should parse, but at the moment it does not:

```sparql
select ?s (?x as ?y) {
  ?s ?p ?x.
}
group by ?s
```

^ The above query string is parsed by Virtuoso but is not parsed by Jena :-/

The relevant section in the standard is <https://www.w3.org/TR/sparql11-query/#sparqlGroupAggregate>.

**Comment by LaurensRietveld** [comment]
Hi @RubenVerborgh , we're bumping into this issue frequently and are thinking about creating a temporary fork that disable these protection mechanisms behind a flag. Would you be up for a PR that does this, or shall we just use the fork until these protection mechanisms are improved?

**Comment by RubenVerborgh** [comment]
A PR is fine, thanks!

**Comment by danielbeeke** [comment]
As discussed with @rubensworks, I will work on this issue via the Comunica Association.

**Comment by rubensworks** [comment]
@LaurensRietveld Version 3.5.0 has been released with the changes from @danielbeeke in #145. Can you confirm that the requirements for this bounty have been met?

**Comment by LaurensRietveld** [comment]
Hi @rubensworks and @danielbeeke I think something went wrong with releasing the latest version: it's not on NPM yet.

Code-wise I agree with the changes. Just wanted to include the latest version in some of our test suites to ensure nothing regressed.

**Comment by rubensworks** [comment]
Ah indeed, it's bumped on GH, but not updated on npm indeed. @RubenVerborgh is it possible something went wrong during the publish step?

**Comment by LaurensRietveld** [comment]
One other think I noticed (not posting it to the merge request as it's closed):

I like the scope of the flag, saying we only want syntactically correct queries. Given that argumentation, I'd expect errors to be thrown for syntactically invalid SPARQL 1.1 and SPARQL-star queries (of course depending on whether sparql-star parsing is enabled).
I'm not sure how the [ensureSparqlStar](https://github.com/RubenVerborgh/SPARQL.js/blob/main/lib/sparql.jison#L362) maps to this, considering this check is skipped `skipValidation` is set

**Comment by RubenVerborgh** [comment]
Published now, sorry!

**Comment by rubensworks** [comment]
> I like the scope of the flag, saying we only want syntactically correct queries. Given that argumentation, I'd expect errors to be thrown for syntactically invalid SPARQL 1.1 and SPARQL-star queries (of course depending on whether sparql-star parsing is enabled).
> I'm not sure how the ensureSparqlStar maps to this, considering this check is skipped skipValidation is set

Good point. So with these changes, if `skipValidation` is enabled, but `sparqlStar` is not, then no errors will be thrown if (syntatical) SPARQL* queries are parsed, which may not be intended?

Was this the intention @danielbeeke?

**Comment by danielbeeke** [comment]
It was not the intention to disable errors while having `skipValidation = true && sparqlStar = false`

I have created a new merge request.
See https://github.com/RubenVerborgh/SPARQL.js/pull/147

**Comment by rubensworks** [comment]
@LaurensRietveld Now that @147 has been merged, do you agree that this issue can be closed?

**Comment by LaurensRietveld** [comment]
Yes, looks good, thanks!

**Comment by rubensworks** [comment]
Perfect! @LaurensRietveld @danielbeeke I'll mail both of you early next week about the next steps in the bounty process.
