### ISSUE TITLE
Use smaller data factory dependency

### ISSUE THREAD

**Issue by rubensworks** [RubenVerborgh/SPARQL.js#121]
@jacoscaz is working on a custom Comunica config for [Quadstore](https://github.com/beautifulinteractions/node-quadstore), where a priority is to have small bundle sizes.

After some improvements in Comunica, this shows the largest current dependencies:
![Screen-Shot-2020-11-02-at-15 55 46](https://user-images.githubusercontent.com/440384/97883859-adb13780-1d25-11eb-97bb-56a806ecc20a.png)

N3 seems to be quite large here, but actually isn't needed.
N3 is only used here as a dependency of SPARQL.js, since it's parsers and serializers were excluded from the Comunica config.
SPARQL.js only seems to use N3 for its data factory implementation.

This issue is to discuss the possibility to migrate to another (smaller) data factory dependency.
For instance, [rdf-data-factory](https://github.com/rubensworks/rdf-data-factory.js) could be used, as this dependency is already in use by all other Comunica dependencies. (It's the smallest data factory AFAIK)

**Comment by RubenVerborgh** [comment]
> This issue is to discuss the possibility to migrate to another (smaller) data factory dependency.

Definitely. Also, that should be smaller _default_ factory; I think/hope that SPARQL.js already allows injecting.

Another thing we could do is enable tree shaking, but I think `rdf-data-factory` is the quickest and best way forward for this old codebase.

**Comment by jacoscaz** [comment]
Hi all! Shall I work on a PR for this? Would it be ok with you @RubenVerborgh?

**Comment by RubenVerborgh** [comment]
Yes, please!
