### ISSUE TITLE
PR #104 Follow-up - Add option to force print datatype on string/integer

### ISSUE THREAD

**Issue by antoine-morvan** [RubenVerborgh/SPARQL.js#135]
Following my comment on the PR https://github.com/RubenVerborgh/SPARQL.js/pull/104 I figured it's better to create new issue.

The point of the PR was to no generate `^^xsd:string` since this is the default datatype of quoted tokens in SPARQL.

However we (my team use case) need this for at least one endpoint that does not interpret `"PARIS"` and `"PARIS"^^xsd:string` in the same way.

I understand that SPARQL.js is not at fault for just following the standard, and that the endpoint I'm using is faulty for not doing so.

Still, I can implement an option in the Generator that would "force" print the datatype (can be done for integers too).

However before I start I'd like to have the author's opinion on the idea, especially if there is hope seeing the PR merged, or if this is a no go as it's not standard-required.

Best.

**Comment by RubenVerborgh** [comment]
I see; let's have an `explicitDatatype` option.
