### ISSUE TITLE
Remove built-ins from SparqlParser.js

### ISSUE THREAD

**Issue by tpluscode** [RubenVerborgh/SPARQL.js#139]
The module `lib/SparqlParser.js` wants to `require` the node modules `fs` and `path`

This is a bit problematic in my setup where I want run browser tests for a component which uses the parser. It is running rollup and, while commonjs can be easily transformed, I'm having a hard time setting it up so that it doesn't choke on the built-in modules.

Would it be possible to move the function `exports.main = function commonjsMain (args) {}` somewhere else?

**Comment by RubenVerborgh** [comment]
Mmm, the prob is that `lib/SparqlParser.js` is autogenerated.

**Comment by tpluscode** [comment]
Thought so :(. I did a dirty, hacky rewrite in the test setup for now...

**Comment by jacoscaz** [comment]
I suspect that this is also what is preventing usage of `quadstore-comunica` in Deno:

```sh
error: Uncaught ReferenceError: require is not defined
    if (require.main === module) {
    ^
    at https://cdn.skypack.dev/-/sparqljs@v3.5.2-dsMDqK77bLuGqQk32ifA/dist=es2019,mode=imports/optimized/sparqljs.js:1900:5
    at createCommonjsModule (https://cdn.skypack.dev/-/sparqljs@v3.5.2-dsMDqK77bLuGqQk32ifA/dist=es2019,mode=imports/optimized/sparqljs.js:204:6)
    at https://cdn.skypack.dev/-/sparqljs@v3.5.2-dsMDqK77bLuGqQk32ifA/dist=es2019,mode=imports/optimized/sparqljs.js:239:22
```

Otherwise, Skypack's version available at https://cdn.skypack.dev/sparqljs@v3.5.2 should be good to go. I can't think of anything outside super-hacky solutions... @tpluscode how have you addressed this?

**Comment by tpluscode** [comment]
@jacoscaz this is super specific to [@web/test-runner](https://www.npmjs.com/package/@web/test-runner) https://github.com/zazuko/rdfjs-elements/blob/27c7b29274077a6f6e281d94fcf747b06bb55ddf/web-test-runner.config.mjs#L23-L32

**Comment by jacoscaz** [comment]
@RubenVerborgh would you accept a PR that manually removes that code? It's bound to be at least somewhat hacky, though.

**Comment by RubenVerborgh** [comment]
This whole library has always been a hack in the first place (was supposed to be a parser for 1 summer until something better was written). So yeah, with a repeatable build process, why not!

**Comment by tpluscode** [comment]
> for 1 summer

8 years ago :D
