### ISSUE TITLE
SPARQL Generator error "Cannot read property 'termType' of undefined"

### ISSUE THREAD

**Issue by alexander-schulze** [RubenVerborgh/SPARQL.js#140]
Dear RubenVerborgh,
when running the code I get the following error "Uncaught TypeError: Cannot read property 'termType' of undefined", while trying to re-generate the SPARQL. Is this a known issue and how could I fix it? The parser works, but the generator fires this issue. I'm using VSC 1.54.3 with node 12.20 on a macOS 10.13.6 (High Sierra). 
Thanks in advance for looking at that and giving a hint.
Best Regards,
Alex

**Comment by RubenVerborgh** [comment]
Do you have the steps to reproduce?

**Comment by alexander-schulze** [comment]
I ran the following steps:

- created a blank new node.js project (node 12.20.0, npm 7.7.6, V8: 7.8.279.23-node.45)
- ran npm init, initial package.json:

```
{
  "name": "sparqljs-test",
  "version": "1.0.0",
  "description": "SPARQLJS Test",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/innotrade/sparqljs-test.git"
  },
  "keywords": [
    "SPARQL",
    "JS"
  ],
  "author": "Alexander Schulze",
  "license": "MIT",
  "bugs": {
    "url": "https://github.com/innotrade/sparqljs-test/issues"
  },
  "homepage": "https://github.com/innotrade/sparqljs-test#readme",
  "dependencies": {
    "sparqljs": "^3.4.1"
  }
}

```
- ran npm i sparqljs --save
- created an index.js and pasted your example from https://www.npmjs.com/package/sparqljs
- debugged it in VSC 1.54.3
- got the following error message:

```
/Users/alexanderschulze/.nvm/versions/node/v12.20.0/bin/node ./index.js
Process exited with code 1
Uncaught TypeError: Cannot read property 'termType' of undefined
```

The parser works fine, I can see the resulting SPARQL AST object.
The generator.stringify(parsedQuery); raises the above exception.

```
var generator = new SparqlGenerator({
  /* prefixes, baseIRI, factory, sparqlStar */
});
parsedQuery.variables = ["?mickey"];
var generatedQuery = generator.stringify(parsedQuery);
```

Thanks in advance for your support!

**Comment by alexander-schulze** [comment]
My launch.json:
```
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "pwa-node",
      "request": "launch",
      "name": "Launch Program",
      "runtimeVersion": "12.20.0",
      "skipFiles": ["<node_internals>/**"],
      "program": "${workspaceFolder}/index.js"
    }
  ]
}
```

**Comment by alexander-schulze** [comment]
Missed to say thanks for the quick response. Just granted you access to @innotrade/sparqljs-test.

**Comment by alexander-schulze** [comment]
Debugged it and found it, the `parsedQuery.variables = ['?mickey'];` is causing the error.
I will play more with it and give you feedback. Would be interested in a cooperation on that one.

**Comment by AlexeyMz** [comment]
@alexander-schulze SPARQL.js uses [RDF/JS spec](https://rdf.js.org/data-model-spec/) to represent RDF terms including variables, so you need to use RDF term factory to create variable in this case:
```js
import { DataFactory } from 'rdf-data-factory';
var generator = new SparqlGenerator({
  /* prefixes, baseIRI, factory, sparqlStar */
});
var dataFactory = new DataFactory();
parsedQuery.variables = [dataFactory.variable("mickey")];
var generatedQuery = generator.stringify(parsedQuery);
```
