### ISSUE TITLE
Use this lib with Turtle in-memory

### ISSUE THREAD

**Issue by Melchyore** [RubenVerborgh/SPARQL.js#141]
Hello!

I have a turtle (string) stored in a variable and I wonder if I can run queries on it using this lib... I couldn't find any example!

Thanks!

**Comment by RubenVerborgh** [comment]
This library is just for parsing SPARQL queries.

You would need to 1) parse the Turtle (see for instance N3.js) and 2) use query engine (such as Comunica).
