### ISSUE TITLE
support for SPARQL query executer

### ISSUE THREAD

**Issue by jayeshdesai4520** [RubenVerborgh/SPARQL.js#143]
Hi, I was trying to find a method for querying triplestore using SPARQL
It would be great if this library also supports it
Thanks

**Comment by rubensworks** [comment]
This lib is just a parser, it does not aim to do anything more.

Other projects (that use SPARQL.js) exist that do what you need, such as:
* https://github.com/rubensworks/fetch-sparql-endpoint.js/
* https://github.com/comunica/comunica

**Comment by jayeshdesai4520** [comment]
thank you I will look at it.

**Comment by fetahokey** [comment]
> This lib is just a parser, it does not aim to do anything more.
> 
> Other projects (that use SPARQL.js) exist that do what you need, such as:
> 
> * https://github.com/rubensworks/fetch-sparql-endpoint.js/
> * https://github.com/comunica/comunica

&& 🎉 
-  https://www.npmjs.com/package/sparql-http-client
