### ISSUE TITLE
The package does not work as CLI

### ISSUE THREAD

**Issue by vemonet** [RubenVerborgh/SPARQL.js#154]
Hi @rubensworks , we just tried to install and used your library with the CLI following the given instructions, but it does not work

Obviously we followed the instructions from the README

```
npm install -g sparqljs
```

Then the docs said to run this:

```
$ sparql-to-json --strict query.sparql
```

But the `sparql-to-json` command does not exists... 

I can only find a `sparqljs` CLI command, but it get stuck when trying to run it obviously

Would it be possible to clarify the documentation? Is it supposed to work as CLI? Is there any additional things to do to make it work?
I am not an expert in JS but there seems to be an issue with the packaging of the CLI part

This was tested on a Ubuntu 20+ and Fedora 16 laptops

Thanks

**Comment by vemonet** [comment]
Here is the `yarn global add` output:

```
yarn global add sparqljs
yarn global v1.22.18
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...

warning Your current version of Yarn is out of date. The latest version is "1.22.19", while you're on "1.22.18".
success Installed "sparqljs@3.5.2" with binaries:
      - sparqljs
Done in 0.92s.
```


It clearly shows that the bin installed has `sparqljs` as name (which would be the practical and non ambiguous choice, much better that needing to know that the CLI name is different that the package name...)

And it's different than what was defined in the package.json... https://github.com/RubenVerborgh/SPARQL.js/blob/main/package.json#L21

**Comment by vemonet** [comment]
Yes, it only get stuck when no argument are provided

**Comment by RubenVerborgh** [comment]
It's not stuck, it's expecting input from STDIN. I.e., type your query and finish with Ctrl+D 🙂
