### ISSUE TITLE
Cannot resolve relative IRI _:0b80039906942cfccf42dfac0e3fb120 because no base IRI was set. (skipValidation is not working)

### ISSUE THREAD

**Issue by agustaf9** [RubenVerborgh/SPARQL.js#175]
When parsing this query: `DESCRIBE <_:0b80039906942cfccf42dfac0e3fb120>` I get the error `Cannot resolve relative IRI _:0b80039906942cfccf42dfac0e3fb120 because no base IRI was set.`

The error still happens when adding `skipValidation` as shown in the ReadMe.

**Comment by agustaf9** [comment]
I would propose something like this as a solution, but I am not familiar with how the jison file was built.
https://github.com/agustaf9/SPARQL.js/blob/01d2d3fd0d537d2c2a477b3c8a242b3fa754fc67/lib/sparql.jison#L62-L64

**Comment by RubenVerborgh** [comment]
This looks like a broken query to me, so correct behavior: https://www.w3.org/TR/sparql11-query/#rIRIREF

What would you consider correct behavior for this case?

**Comment by agustaf9** [comment]
Fuseki/Jena assigns system identifiers to blank nodes, this query would allow me to describe a blank node

**Comment by RubenVerborgh** [comment]
Looks like a Fuseki/Jena bug to me then; the query would need to be fixed.
