### ISSUE TITLE
Parsing of prefixes

### ISSUE THREAD

**Issue by Jonas-WMDE** [RubenVerborgh/SPARQL.js#20]
Sorry to bother you again : )
Is there a reason why the prefixes are resolved within the triples when parsing a SPARQL query?
I think it unnecessary bloats the SPARQL Object and it would be very easy to look them up when needed.

Kind regards,
Jonas

**Comment by RubenVerborgh** [comment]
Well, that's the job of the parser, to make sure people don't have to look up things anymore :wink:

Another way to look at this is that the job of the parser is to abstract the syntax: two queries that just differ in the prefixes used, are in fact identical queries.

**Comment by Jonas-WMDE** [comment]
Yes, that is true.
Would it be difficult to have a parser option that disables resolving?

Thanks,
Jonas

**Comment by RubenVerborgh** [comment]
This could be done with a switch; would be a matter of skipping [this line](https://github.com/RubenVerborgh/SPARQL.js/blob/a353322404ca34120da8bc93961020648fc3d45c/lib/sparql.jison#L815).
