### ISSUE TITLE
Support for BIND CONCAT

### ISSUE THREAD

**Issue by imranazad** [RubenVerborgh/SPARQL.js#23]
Is there support for BIND CONCAT? I couldn't find any tests that illustrate how to do a bind concat with variables.

**Comment by RubenVerborgh** [comment]
@imranazad Is this still an issue? (It's not fully clear why you closed.)

**Comment by imranazad** [comment]
@RubenVerborgh Thanks Ruben, it's no longer an issue, I managed to find some resources that explained how the BIND and CONCAT can be used together.
