### ISSUE TITLE
When generating SPARQL use prefixes

### ISSUE THREAD

**Issue by JonasKress** [RubenVerborgh/SPARQL.js#24]
I think it would be nice to use prefixes when generating entities of a SPARQL query and maybe also delete prefixes from the list that are not actually in use. 

So in case of Wikidata this: 
http://www.wikidata.org/prop/direct/P31 

would be rendered as:
wdt:P31

What do you think?
It could also be an option in the generator.

Cheers,
Jonas

**Comment by RubenVerborgh** [comment]
Seems like a good idea!

**Comment by Jonas-WMDE** [comment]
Would you implement this, because I think I would just mess up your code ?-)
