### ISSUE TITLE
Disable (minor) query rewrites by default

### ISSUE THREAD

**Issue by aindlq** [RubenVerborgh/SPARQL.js#35]
Let's say we have a simple query like:

```sparql
SELECT * WHERE {
  { ?s ?p ?o. }
  ?a ?b ?c .
}
```
With the last SPARQL.js it is parsed to: 

```json
{
  "queryType": "SELECT",
  "variables": [
    "*"
  ],
  "where": [
    {
      "type": "bgp",
      "triples": [
        {
          "subject": "?s",
          "predicate": "?p",
          "object": "?o"
        },
        {
          "subject": "?a",
          "predicate": "?b",
          "object": "?c"
        }
      ]
    }
  ],
  "type": "query",
  "prefixes": {}
}
```

Which doesn't correspond to the original query, if I serialize it, the result will be: 

```sparql
SELECT * WHERE {
  ?s ?p ?o.
  ?a ?b ?c .
}
```

This missing group sometimes can be significant, e.g. in my use-case I'm trying to apply blazegraph(https://wiki.blazegraph.com/wiki/index.php/QueryHints) query hint to the subgroup.

**Comment by RubenVerborgh** [comment]
> This missing group sometimes can be significant

For this specific case, I disagree: the algebra transformations performed by the parser are explicitly listed in the SPARQL 1.1 specification, and they are just not significant for SPARQL 1.1 semantics. However, some query engines can indeed attach a more specific interpretation.

However, in general, I don't think SPARQL.js should perform such rewritings by default (as it does now). So I will extend the scope of this issue to cover that.

**Comment by RubenVerborgh** [comment]
See #38.
