### ISSUE TITLE
Way to convert query object back to query string?

### ISSUE THREAD

**Issue by yamalight** [RubenVerborgh/SPARQL.js#4]
Did I understood correctly from code that currently there's no way in the lib to convert query object back into query string?

**Comment by RubenVerborgh** [comment]
That's indeed correct. I'm currently not planning this feature, but pull requests are welcome.

**Comment by yamalight** [comment]
Aha, thanks for clarifying. Will most likely do a PR once I'm happy with what I've got :)

**Comment by RubenVerborgh** [comment]
Really? That would be most awesome!

**Comment by yamalight** [comment]
Okay, I'm more than half way through with string generator - 65% of test queries are now properly generated from objects. Just need to finish the rest 35% (or rather ~34% since 2 reported queries are not parsed properly at the moment) and will do a PR.

**Comment by RubenVerborgh** [comment]
That's quite impressive! I'll try to fix the two bugs you reported tonight or tomorrow.

**Comment by yamalight** [comment]
That'd be awesome! 
Then I can do 100% conversion covered by tests which would be just perfect :)

**Comment by yamalight** [comment]
So, I'd finished the generator, it works now for all queries aside from `in.sparql` (because of the missing variables in filters, bug #5) and `sparql-17-4-2-5.sparql` (because of the escaping characters, bug #7)

**Comment by yamalight** [comment]
So, I pushed all the stuff I coded so far [here](https://github.com/yamalight/SPARQL.js/commits/master). Will wait until last two queries are fixed and then will make a PR.

**Comment by RubenVerborgh** [comment]
Thanks. I'm working on this today!

**Comment by RubenVerborgh** [comment]
Could you perhaps change the chained `if else if else` structures to `switch` statements?
Also, I'll probably use my own code style from other projects (which I've been unable to apply here, because of the generated code).

**Comment by yamalight** [comment]
Okay, #7 was fixed by escaping backslashes. So, the only query that does not passes tests is now `in.sparql`, waiting for your fix.

**Comment by yamalight** [comment]
@RubenVerborgh I'm planning to do a bit of refactoring once all the tests are passing. 
On the code style - just used something that was fitting for sparql.js so that my code looks as close as possible to what already existed :) If you push your rules, I can reformat my code to match them.

**Comment by RubenVerborgh** [comment]
#5, #6, #8, right? Will be looking at them shortly.

**Comment by yamalight** [comment]
@RubenVerborgh only #5 is blocker. 
#6 and #8 do not really affect query re-generation since produced query is then parsed to the same structure that was produced initially (due to related bugs).

**Comment by yamalight** [comment]
okay, refactored the code, looks much nicer now. waiting on your fix for #5 :)

**Comment by RubenVerborgh** [comment]
Done, now up to you :wink:
(Will now start fixing the remaining issues.)

**Comment by yamalight** [comment]
Okay, just opened a PR. All queries now pass generation and re-parsing.

**Comment by yamalight** [comment]
Now that I'm thinking, it's probably a good idea to add the description of how it works to readme..

**Comment by RubenVerborgh** [comment]
Awesome, thanks for this.

**Comment by yamalight** [comment]
Can you please publish new version on npm? :)

**Comment by RubenVerborgh** [comment]
Of course, but please give me some time still to fix #8 (working on it) and merge. Probably this weekend at earliest, since I'm traveling at the moment.

**Comment by yamalight** [comment]
sounds good, thanks!
