### ISSUE TITLE
Parsing simple erroneous queries can take exponential time

### ISSUE THREAD

**Issue by lucaswerkmeister** [RubenVerborgh/SPARQL.js#41]
@JonasKress noticed that if you simply type `ddddddddddddddddddddddddddddddddd` (or any other letter) on query.wikidata.org, the tab hangs. It seems that SPARQL.js takes exponential time (twice as long for each letter) to parse such a “query” (before reporting a parse error):

```bash
$ for i in {20..30}; do start=$SECONDS; printf '%*s' $i | tr ' ' 'x' | sparqljs &>/dev/null; end=$SECONDS; printf '%2d: %d s\n' $i $((end-start)); done
20: 0 s
21: 0 s
22: 1 s
23: 1 s
24: 2 s
25: 3 s
26: 7 s
27: 14 s
28: 28 s
29: 56 s
30: 112 s
```

Do you think it’s possible to improve this?

**Comment by RubenVerborgh** [comment]
Which browser? I cannot reproduce a hanging tab this in Chrome.

Unfortunately, this seems like a bug in Jison (https://github.com/zaach/jison), the underlying parser generator.

**Comment by lucaswerkmeister** [comment]
Firefox, but as you can see I timed it in Node.js (v4.2.6). The hang in the browser happens once you release the key and wait for a bit.

**Comment by RubenVerborgh** [comment]
The problem is definitely real; my ability to fix it is limited though. It's really a bug of the underlying parser generator, which unfortunately is no longer actively maintained.

I might design some heuristics for this particular case (= query starts with a clearly invalid token).

**Comment by lucaswerkmeister** [comment]
Perhaps you can help Jison out with an additional token definition? `:ddddddd` and `?dddddddd` both parse instantaneously, but `dddddd` is not a valid token in SPARQL as far as I can tell.

**Comment by RubenVerborgh** [comment]
It might be waiting for `ddddd` to become `ddddd:foo` or something, which would be a valid token. And defining such an additional token could be in the way of those tokens.
