### ISSUE TITLE
Update Queries with multiple operations are not parsed correctly 

### ISSUE THREAD

**Issue by leipert** [RubenVerborgh/SPARQL.js#49]
Update Queries with multiple operations are not parsed correctly, if any update operation after the first contains prefixes:

This is parseable:
```
PREFIX dc: <http://purl.org/dc/elements/1.1/>
INSERT DATA { <http://example/book1> dc:title "A new book" .} ;
INSERT DATA { <urn:a> <urn:a> <urn:a> .}
```

While this throws an Error:
```
PREFIX dc: <http://purl.org/dc/elements/1.1/>
INSERT DATA { <http://example/book1> dc:title "A new book" .} ;
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
INSERT DATA { <http://example/book2> rdfs:label "A second book" .}
```

According to the [SPARQL Grammar # UpdateUnit](https://www.w3.org/TR/sparql11-query/#rUpdateUnit), the second query is valid:
```
[3]  UpdateUnit ::=  Update
[4]  Prologue   ::=  ( BaseDecl \| PrefixDecl )*
[29] Update     ::=  Prologue ( Update1 ( ';' Update )? )?
```

**Comment by RubenVerborgh** [comment]
You're right, thanks!

**Comment by leipert** [comment]
Is there anything I could help you with, or do you have time to fix it yourself?
At the moment we work around it, by prepending all prefixes, so no need to hurry ;)

Thanks for the great work and fast response, as always!

**Comment by RubenVerborgh** [comment]
Fixed :wink:

**Comment by RubenVerborgh** [comment]
Nope, the situation is exactly the same as when they are not split. The prefix order is respected for IRI resolution, and only the final prefix IRIs are returned.
