### ISSUE TITLE
Variables in `IN` expressions are not parsed

### ISSUE THREAD

**Issue by yamalight** [RubenVerborgh/SPARQL.js#5]
Either it's me missing something obvious, or [in.sparql](https://github.com/RubenVerborgh/SPARQL.js/blob/master/queries/in.sparql) query is [parsed](https://github.com/RubenVerborgh/SPARQL.js/blob/master/test/parsedQueries/in.json) wrongly.
String query has this parts:
`FILTER (?a IN (1, 2, 3))`
`FILTER (?c NOT IN (1, 2, 3))`

JSON representation looks like this:
```json
{
  "type": "filter",
  "expression": {
    "type": "operation",
    "operator": "in",
    "args": [
      "\"1\"^^http://www.w3.org/2001/XMLSchema#integer",
      "\"2\"^^http://www.w3.org/2001/XMLSchema#integer",
      "\"3\"^^http://www.w3.org/2001/XMLSchema#integer"
    ]
  }
}
```

And second one:
```json
{
  "type": "filter",
  "expression": {
    "type": "operation",
    "operator": "notin",
    "args": [
      "\"1\"^^http://www.w3.org/2001/XMLSchema#integer",
      "\"2\"^^http://www.w3.org/2001/XMLSchema#integer",
      "\"3\"^^http://www.w3.org/2001/XMLSchema#integer"
    ]
  }
}
```

Is it me, or is the variables (?a in case 1, ?c in case 2) are really missing from args?

**Comment by RubenVerborgh** [comment]
Thanks for reporting, definitely a bug!

**Comment by yamalight** [comment]
@RubenVerborgh looks like you can expect a number of bugs reported in coming days :)

**Comment by RubenVerborgh** [comment]
@yamalight Thanks for your help :smile:

**Comment by yamalight** [comment]
you might want to re-generate in.json as well ;)

**Comment by RubenVerborgh** [comment]
That's in the commit, right?
