### ISSUE TITLE
Update Queries with trailing semicolon should be allowed

### ISSUE THREAD

**Issue by leipert** [RubenVerborgh/SPARQL.js#51]
Sorry to bother you again, but this is one where the [grammar](https://www.w3.org/TR/sparql11-query/#rUpdate) does not make sense:
```
[29] Update     ::=  Prologue ( Update1 ( ';' Update )? )?
```
which theoretically means that
```
INSERT DATA { <http://example/book1> <urn:label> "A new book" .} ;
```
and even
```
INSERT DATA { <http://example/book1> <urn:label> "A new book" .} ; PREFIX a: <urn:a>
```
should be allowed.

While the second case seems not the useful, the first case is even mentioned in the [spec document](https://www.w3.org/TR/sparql11-update/#updateLanguage):
> Multiple operations are separated by a ';' (semicolon) character. A semicolon after the last operation in a request is optional.

**Comment by leipert** [comment]
Even
```
PREFIX a: <urn:a>
```
is an allowed update query 🙁

**Comment by RubenVerborgh** [comment]
Aargh, why 😆

**Comment by RubenVerborgh** [comment]
Not seeing how the production rules can put a semicolon at the end, but the spec indeed says it.

**Comment by RubenVerborgh** [comment]
Fixed. Let me know if you're testing more things—if not, I'll release 2.0.2.

**Comment by leipert** [comment]
No, otherwise everything is very reliable and I just stumbled across those two issues.
