### ISSUE TITLE
Reified statements support (SPARQL*)

### ISSUE THREAD

**Issue by futpib** [RubenVerborgh/SPARQL.js#65]
There is an extension to SPARQL called SPARQL*. It allows using statements as subjects and objects and looks like this:

```sparql
SELECT ?age ?src WHERE {
   ?bob foaf:name "Bob" .
   <<?bob foaf:age ?age>> dct:source ?src .
}
```

More info and whitepaper: https://wiki.blazegraph.com/wiki/index.php/Reification_Done_Right

**Comment by RubenVerborgh** [comment]
Indeed, but this library focuses on spec-compatible SPARQL 1.1. Even if we were to parse SPARQL*, there is no in-memory representation for it yet.
