### ISSUE TITLE
Add space between integer literals and periods

### ISSUE THREAD

**Issue by lucaswerkmeister** [RubenVerborgh/SPARQL.js#66]
Consider the following example query:

```sparql
SELECT * WHERE {
  ?s1 ?p1 1 .
  ?s2 ?p2 2 .
}
LIMIT 1
```

When parsing and then regenerating it, SPARQL.js will remove the spaces between the integer literals and the periods:

```sparql
SELECT * WHERE {
  ?s1 ?p1 1.
  ?s2 ?p2 2.
}
LIMIT 1
```

However, this query will fail to parse in SPARQL.js, as well as in several SPARQL servers (at least Virtuoso and Blazegraph, but not in Fuseki), because they parse `1.` as a decimal literal (with no decimal digits).

The SPARQL production for [`DECIMAL`](https://www.w3.org/TR/sparql11-query/#rDECIMAL) requires *one* or more digits after the decimal point, so I think implementations failing to parse the second query are technically not compliant with the standard – but still, for compatibility with both itself and several major SPARQL servers, it would nevertheless be nice if SPARQL.js could resolve this ambiguity at the point of SPARQL generation, by separating integer literals and periods with spaces.

(See [T206910](https://phabricator.wikimedia.org/T206910) for the corresponding issue on our own bug tracker.)

**Comment by RubenVerborgh** [comment]
Thanks for reporting!

> However, this query will fail to parse in SPARQL.js

So this is the real issue. Filed #67.

> as well as in several SPARQL servers (at least Virtuoso and Blazegraph, but not in Fuseki)

Mmm, not good, we should all follow the spec.

> if SPARQL.js could resolve this ambiguity at the point of SPARQL generation, by separating integer literals and periods with spaces.

I don't think it's ambiguous, but it is tricky to implement this right (I had the same situation for Turtle with N3.js, and that is a streaming parser so it was even more difficult).

So I think we should indeed follow your suggestion, but also just fix the parser.

**Comment by lucaswerkmeister** [comment]
I wasn’t quite confident enough in my reading of the spec, but thanks for filing #67 :) adjusting both parser and generator sounds good to me.

**Comment by RubenVerborgh** [comment]
@lucaswerkmeister Seems like you are using an old version; this has been fixed back in 2016: 7a19244caf9ac65d5ef3e893c35843703089fa5f.

**Comment by lucaswerkmeister** [comment]
Ah, I see now why we’re not getting the package from npm – it looks like it needs to browserified first, the version on npm can only be used with Node. Upgrade pending in [I7d002c7b1f](https://gerrit.wikimedia.org/r/484266).

**Comment by RubenVerborgh** [comment]
@lucaswerkmeister Great, I have also filed https://github.com/RubenVerborgh/SPARQL.js/issues/76 so you can use the npm module in the future.

**Comment by lucaswerkmeister** [comment]
Cool, thanks! I wasn’t sure if I should open an issue for that or not, so I just settled on an open-ended comment instead ^^
