### ISSUE TITLE
Remove parens and multi-line when formatting VALUES

### ISSUE THREAD

**Issue by nyurik** [RubenVerborgh/SPARQL.js#68]
Per issue [reported for Wikidata Query Service](https://phabricator.wikimedia.org/T210692), please do not add parenthesis to a single value `VALUES` list. Examples:

### Original text
```
SELECT * WHERE {
  VALUES ?a { wd:Q1 wd:Q2 ... }
}
```

### Desired results
```
# short list
SELECT * WHERE {   VALUES ?a { wd:Q1 wd:Q2 } }
```
```
# long list
SELECT * WHERE {
  VALUES ?a {
    wd:Q1 wd:Q2 wd:Q1 wd:Q2 wd:Q1 wd:Q2 wd:Q1 wd:Q2 wd:Q1 wd:Q2 wd:Q1 wd:Q2
    wd:Q1 wd:Q2 wd:Q1 wd:Q2 wd:Q1 wd:Q2 wd:Q1 wd:Q2 wd:Q1 wd:Q2 wd:Q1 wd:Q2
  }
}
```

### Current result
```
SELECT * WHERE {
  VALUES (?a) {
    (wd:Q1)
    (wd:Q2)
  }
}
```

**Comment by nyurik** [comment]
@RubenVerborgh thanks you for such a quick response!!! I noticed that in #69 you only dealt with the parents, not the multiline issue, but you closed this one. Should multiline be a separate issue? Thx!!

**Comment by RubenVerborgh** [comment]
It auto-closed, best to create a new one indeed.
