### ISSUE TITLE
Allow custom functions

### ISSUE THREAD

**Issue by dwhitney** [RubenVerborgh/SPARQL.js#77]
Is there any way to augment the parser to allow for custom function names? For example imagine I'd like to do something like: 

```
SELECT ?reversed
WHERE
{ 
  ?s ?p ?o . 
  BIND(REVERSE(?o) as ?reversed
}
```
Where `REVERSE` will be supplied by myself in a runtime evaluator (sparql-engine). Any help would be appreciated. Thanks!

**Comment by RubenVerborgh** [comment]
The only way to currently do that is to for the repository. It would indeed be nice to make this customizable.

**Comment by dwhitney** [comment]
I need this feature for the work I'm doing. I'll see what I can get going and send a PR for your review if I go this direction.

**Comment by dwhitney** [comment]
Actually this already seems to work?
```
PREFIX foo: <http://foo.com#>
SELECT *
WHERE
{
  ?s ?p ?o .
  BIND(foo:FOO(?s, ?p, ?o) as ?foo) .
}
```
parses to 
```json
{
  "queryType": "SELECT",
  "variables": [
    "*"
  ],
  "where": [
    {
      "type": "bgp",
      "triples": [
        {
          "subject": "?s",
          "predicate": "?p",
          "object": "?o"
        }
      ]
    },
    {
      "type": "bind",
      "variable": "?foo",
      "expression": {
        "type": "functionCall",
        "function": "http://foo.com#FOO",
        "args": [
          "?s",
          "?p",
          "?o"
        ],
        "distinct": false
      }
    }
  ],
  "type": "query",
  "prefixes": {
    "foo": "http://foo.com#"
  }
}
```

am I missing something (kinda new to SPARQL)?

**Comment by RubenVerborgh** [comment]
BIND is an existing SPARQL function, not a custom one.

**Comment by dwhitney** [comment]
well yeah - I'm interested in getting the "foo:FOO" functionality. Not sure what that's called. But anyway, this is what I wanted.
