### ISSUE TITLE
CREATE query not picking up iri correctly

### ISSUE THREAD

**Issue by JuniperChicago** [RubenVerborgh/SPARQL.js#79]

**Comment by JuniperChicago** [comment]
When using `CREATE GRAPH <IRI>`, the parser returns `{ type: 'create', silent: false, graph: 'GRAPH' }`. I am not well versed in JISON, but I found the offset (or whatever) is wrong in the compiled file. When `case 45` (somewhere around line 224) of SparqlParser.js is changed from `this.$ = { type: 'create', silent: !!$$[$0-2], graph: $$[$0-1] };` to `this.$ = { type: 'create', silent: !!$$[$0-2], graph: $$[$0] };`... it works great.

**Comment by RubenVerborgh** [comment]
Woops, this has never worked indeed. Good find!

**Comment by JuniperChicago** [comment]
I just fixed it and added tests... I will do a push request in a few minutes.

**Comment by RubenVerborgh** [comment]
Unfortunately I beat you to it, but thanks for your help 🙂

**Comment by JuniperChicago** [comment]
NP. Thanks.
