### ISSUE TITLE
Version 2.2.2 breaks with webpack

### ISSUE THREAD

**Issue by rubensworks** [RubenVerborgh/SPARQL.js#81]
It looks like since version 2.2.2, webpack builds are failing, possibly because of this commit: https://github.com/RubenVerborgh/SPARQL.js/commit/f211398d758bde0911cdd9f1370683cd73f2b823

```
ERROR in /home/travis/build/comunica/comunica/node_modules/fetch-sparql-endpoint/node_modules/sparqljs/lib/SparqlParser.js
Module not found: Error: Can't resolve 'fs' in '/home/travis/build/comunica/comunica/node_modules/fetch-sparql-endpoint/node_modules/sparqljs/lib'
 @ /home/travis/build/comunica/comunica/node_modules/fetch-sparql-endpoint/node_modules/sparqljs/lib/SparqlParser.js 4887:17-30
 @ /home/travis/build/comunica/comunica/node_modules/fetch-sparql-endpoint/node_modules/sparqljs/sparql.js
 @ /home/travis/build/comunica/comunica/node_modules/fetch-sparql-endpoint/lib/SparqlEndpointFetcher.js
 @ /home/travis/build/comunica/comunica/node_modules/fetch-sparql-endpoint/index.js
 @ ../actor-query-operation-sparql-endpoint/lib/ActorQueryOperationSparqlEndpoint.js
 @ ../actor-query-operation-sparql-endpoint/index.js
 @ ./engine-default.js
 @ ./index-browser.js
 @ multi @babel/polyfill ./index-browser.js
```

Full log: https://travis-ci.org/comunica/comunica/jobs/505234208

**Comment by RubenVerborgh** [comment]
Had that too; blamed webpack update. Any evidence for webpack respecting
the browsers field?

**Comment by rubensworks** [comment]
As far as I know, webpack respects the browser field according to this document: https://github.com/defunctzombie/package-browser-field-spec
(I can't find it atm in the webpack docs, but they clearly mention it all over the place in their GitHub issues)

So the `require('fs')` used to be ignored as defined by the browser field.

**Comment by RubenVerborgh** [comment]
Indeed, here's evidence: https://webpack.js.org/configuration/resolve/#resolvealiasfields

Sorry for breakage; I had no idea webpack listened to this one (and it is confusing that it does, given webpack.config).

**Comment by RubenVerborgh** [comment]
v2.2.3

**Comment by rubensworks** [comment]
Thanks! Things are working correctly again now :-)
