### ISSUE TITLE
Check whether variables are free when needed

### ISSUE THREAD

**Issue by rubensworks** [RubenVerborgh/SPARQL.js#82]
According to the spec, the following query has an invalid syntax:

```sparql
SELECT (1 AS ?X )
  {
    SELECT (2 AS ?X ) {}
  }
```

However, SPARQL.js parses it without throwing an error.

From [18.2.1 Variable Scope](https://www.w3.org/TR/sparql11-query/#variableScope)): 

> The variable v must not be in-scope at the point of the (expr AS v) form.

Relevant test: https://www.w3.org/2009/sparql/docs/tests/data-sparql11/syntax-query/manifest#test_65

_Discovered while running SPARQL 1.1 Query test suite: https://github.com/comunica/comunica/issues/287_

**Comment by rubensworks** [comment]
Similar issue exist for the following queries:

```sparql
PREFIX : <http://www.example.org>
SELECT *
 WHERE {
    :s :p ?o .
    :s :q ?o1 .
    BIND((1+?o) AS ?o1)
 }
```

Source: http://www.w3.org/2009/sparql/docs/tests/data-sparql11/syntax-query/manifest#test_60

```sparql
PREFIX : <http://www.example.org>
 SELECT *
 WHERE {
    {
    :s :p ?o .
    :s :q ?o1 .
    }
    BIND((1+?o) AS ?o1)
 }
```

Source: http://www.w3.org/2009/sparql/docs/tests/data-sparql11/syntax-query/manifest#test_61a

```sparql
PREFIX : <http://www.example.org>
SELECT *
  {
    {
       { :s :p ?Y }
       UNION
       { :s :p ?Z }
    }
   BIND (1 AS ?Y)
 }
```

Source: http://www.w3.org/2009/sparql/docs/tests/data-sparql11/syntax-query/manifest#test_62a

```sparql
SELECT (1 AS ?X) (1 AS ?X) {}
```

Source: http://www.w3.org/2009/sparql/docs/tests/data-sparql11/syntax-query/manifest#test_45

**Comment by RubenVerborgh** [comment]
Indeed, checking whether variables are free (or bound) as needed is nothing something that is done yet.

**Comment by RubenVerborgh** [comment]
> has an invalid syntax

Interestingly, I remember leaving it out of scope, because I mainly wanted to parse syntax. Such things were grammar for me; but indeed, it should be checked nonetheless.
