### ISSUE TITLE
Out-of-scope variables in SELECT not throwing error

### ISSUE THREAD

**Issue by rubensworks** [RubenVerborgh/SPARQL.js#83]
According to the spec, the following query has an invalid syntax:

```sparql
SELECT ?o WHERE { ?s ?p ?o } GROUP BY ?s
```

However, SPARQL.js parses it without throwing an error.

Relevant test: http://www.w3.org/2009/sparql/docs/tests/data-sparql11/syntax-query/manifest#test_44

Test message:

> required syntax error : out of scope variable in SELECT from group

_Discovered while running SPARQL 1.1 Query test suite: https://github.com/comunica/comunica/issues/287_

**Comment by RubenVerborgh** [comment]
In what sense is this different from https://github.com/RubenVerborgh/SPARQL.js/issues/82 ?

**Comment by rubensworks** [comment]
#82 is about variables being re-defined, and conflicting.
This issue is about variables being selected that are undefined.
Both are indeed related to scoping, but from a different perspective.
