### ISSUE TITLE
DAWG TestCases basic/term-7 fails

### ISSUE THREAD

**Issue by jorge-agra** [RubenVerborgh/SPARQL.js#86]
The query below, part of dawg TestCases, fails at least in version 2.2.3. It should consider the first dot as a decimal point, according to test description :)

```
PREFIX :     <http://example.org/ns#>
PREFIX xsd:  <http://www.w3.org/2001/XMLSchema#>

# DOT is part of the decimal.
SELECT * { :x ?p 456. . }
```

**Comment by RubenVerborgh** [comment]
Good catch. Will probably need a lookahead in the decimal regex.

**Comment by jorge-agra** [comment]
Hi Ruben,

for my very limited test cases, this change worked, on line 266 of (sparql.jison):

DECIMAL               [0-9]*"."[0-9]+
=>
DECIMAL               [0-9]*"."[0-9]*

As I have a very contained and limited test case, I can **not** be sure this will work for any other situation.

But it seems to accept that a decimal can be:
434.

Instead of always:

434.X

Best regards and thank you for a very nice and usefull lib. 
JA

**Comment by RubenVerborgh** [comment]
Thanks!

However, with the above regex, I'm concerned about the following case:

```
SELECT * { :x ?p 456. :x :y :z. }
```

There, the dot should be seen as statement separator, but the above regex will eat it as a decimal point. That's why we'll likely need a lookahead too, cfr. https://github.com/rdfjs/N3.js/blob/adeef0a13478e4cd74a2a792d411f9a23b31c3b4/lib/N3Lexer.js#L52

**Comment by jorge-agra** [comment]
Greetings,

I am just running your (great) parser against some tests (from w3 council) and found the problem.

I understand that it might not take in consideration all cases you are considering right now. Thats your call of course.

If you have any concrete situation I can be of help, just drop me a message and I will try my best.

Best regards.
JA

**Comment by jorge-agra** [comment]
Well, now i'm very confused. Just checked w3 spec and your implementation of decimal parsing seems to be 100% aligned :/

Sorry for bringing this subject, but took the tests from w3 sparql (the same org right?), and that problem arise.

**Comment by RubenVerborgh** [comment]
Yeah but the spec’s regexes don’t take into account precedence, so it’s not
a contradiction.

**Comment by kasei** [comment]
@jorge-agra to provide some context here, the query you asked about is part of the SPARQL 1.0 test suite. It is one of the (very few) tests that was made invalid by the SPARQL 1.1 spec: decimal values cannot end in a dot anymore (as they could in 1.0). Unfortunately, there are still some cases where older tests like this still appear to be officially sanctioned, but do not represent the current state of the spec.

**Comment by RubenVerborgh** [comment]
Thanks @kasei for resolving this mystery.
