### ISSUE TITLE
DAWG TestCases basic/list-2 fails

### ISSUE THREAD

**Issue by jorge-agra** [RubenVerborgh/SPARQL.js#87]
Sorry to be posting another issue. Can someone help me understand why the parsing is like that in the case below?

DAWG list-2 data:
```
@prefix : <http://example.org/ns#> .
@prefix xsd:        <http://www.w3.org/2001/XMLSchema#> .


:x :list0 () .
:x :list1 ("1"^^xsd:integer) .
:x :list2 ("11"^^xsd:integer "22"^^xsd:integer) .
:x :list3 ("111"^^xsd:integer "222"^^xsd:integer "333"^^xsd:integer) .

```
DAWG list-2 query:

```
PREFIX : <http://example.org/ns#>

SELECT ?p
{ :x ?p (1) . }
```

The result BGPs generated by parsing:

```
[ { subject: 'http://example.org/ns#x',
    predicate: '?p',
    object: '_:b0' },
  { subject: '_:b0',
    predicate: 'http://www.w3.org/1999/02/22-rdf-syntax-ns#first',
    object: '"1"^^http://www.w3.org/2001/XMLSchema#integer' },
  { subject: '_:b0',
    predicate: 'http://www.w3.org/1999/02/22-rdf-syntax-ns#rest',
    object: 'http://www.w3.org/1999/02/22-rdf-syntax-ns#nil' } ]

```

Should not that _:b0 be a var? The parser can't know at parsing time, the id of the bnode that will be created. Right?

Best regards.

**Comment by RubenVerborgh** [comment]
> the id of the bnode that will be created

Blank nodes don't have an ID, so we're good 🙂

The query you wrote is semantically equivalent to

```
PREFIX : <http://example.org/ns#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT ?p {
  :x ?p _:whatever.
  _:whatever rdf:first 1.
  _:whatever rdf:rest rdf:nil.
}
```

The blank node can get any label (as long as it is the same on all three lines). It has only local meaning, and the meaning is independent of the actual query evaluation.

**Comment by jorge-agra** [comment]
Ok. Thanks for explaining. Sorry for bothering with such a basic doubt.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
