### ISSUE TITLE
Generator.stringify() is broken in 3.0.0-beta.0

### ISSUE THREAD

**Issue by white-gecko** [RubenVerborgh/SPARQL.js#90]
So far I was using the sparqljs Generator to create SPARQL Update strings in the following way: 

```
var sparqljs = require("sparqljs@2.2.3")
var updateStructure = {"type":"update","updates":[{"updateType":"insert","insert":[{"triples":[{"subject":"http://aksw.org/NatanaelArndt","predicate":"http://xmlns.com/foaf/0.1/name","object":"\"Natanael Arndt\"","graph":""}],"type":"graph","name":"http://aksw.org/"}]}]}
var generator = new sparqljs.Generator()
var updateString = generator.stringify(updateStructure)
console.log(updateString)
```

The actual and expected output was (can be reproduced on https://npm.runkit.com/sparqljs):

```
INSERT DATA { GRAPH <http://aksw.org/> { <http://aksw.org/NatanaelArndt> <http://xmlns.com/foaf/0.1/name> "Natanael Arndt". } }
```

Since the update to 3.0.0-beta.0 I get the error `value.items is undefined` in this line: https://github.com/RubenVerborgh/SPARQL.js/blob/bd5dfe8cd9f18d326da8897d31763824409aefce/lib/SparqlGenerator.js#L288

This can be reproduced with the following code on https://npm.runkit.com/sparqljs
```
var sparqljs = require("sparqljs@3.0.0-beta.0")
var updateStructure = {"type":"update","updates":[{"updateType":"insert","insert":[{"triples":[{"subject":"http://aksw.org/NatanaelArndt","predicate":"http://xmlns.com/foaf/0.1/name","object":"\"Natanael Arndt\"","graph":""}],"type":"graph","name":"http://aksw.org/"}]}]}
var generator = new sparqljs.Generator()
var updateString = generator.stringify(updateStructure)
console.log(updateString)
```

This issue/new behavior must have been introduced with https://github.com/RubenVerborgh/SPARQL.js/pull/80

**Comment by RubenVerborgh** [comment]
Note that 3.0.0 is a major version update, which comes with API breakage.

We have switched the representation of triples components from strings to RDF/JS-compatible objects. An example is in the README: https://github.com/RubenVerborgh/SPARQL.js#representation

The input value you are providing is still the old input format, which will only work with 2.x versions.

You could migrate to the new input by having 2.x generate the SPARQL query, and then letting 3.x parse it.

**Comment by white-gecko** [comment]
ok, so it is intended to not support strings for the graph iri in this place anymore?

**Comment by RubenVerborgh** [comment]
Indeed, this has been deprecated in favor of RDF/JS.

**Comment by white-gecko** [comment]
Thank you for the clarification.
