### ISSUE TITLE
Parsing issue with SPARQL query on inverse paths in anonymous node

### ISSUE THREAD

**Issue by rubensworks** [RubenVerborgh/SPARQL.js#99]
_Originally reported in by https://github.com/comunica/comunica/issues/677 @jaw111._

There is an odd combination of syntax that is flagged as an error.

```sparql
SELECT *
WHERE {
  ?movie a dbpedia-owl:Film ;
    dbpedia-owl:starring [
      rdfs:label "Brad Pitt"@en ;
      ^dbpedia-owl:starring ?otherMovie
    ] .
}
```

Gives the error:

```
# Parse error on line 21:
...ad Pitt"@en ;      ^dbpedia-owl:starrin
----------------------^
Expecting 'IRIREF', 'PNAME_NS', 'VAR', '}', 'GRAPH', ';', 'a', ']', 'PNAME_LN', '.', got '^'
```

Whilst removing the triple pattern for `a` works just fine:

```sparql
SELECT *
WHERE {
  ?movie
    dbpedia-owl:starring [
      rdfs:label "Brad Pitt"@en ;
      ^dbpedia-owl:starring ?otherMovie
    ] .
}
```

-----

## Bounty

A [bounty](https://comunica.dev/association/bounties/) has been placed on this issue by:

| |
|-|
| [<img alt="Triply" src="https://nightly.triplydb.com/imgs/logos/logo-lg.svg?v=3" height="25">](https://triply.cc/) |
| €272 |

[Click here to learn more](https://comunica.dev/association/bounty_process/) if you're interested in claiming this bounty by resolving this issue.

**Comment by LaurensRietveld** [comment]
This probably isn't related to the type of property path operator, as this one fails as well:

```
prefix : <https://ex.com/>
select * {
:a :a :a ;
  :a [
    :a/:a :a
  ] .
}
```

**Comment by wouterbeek** [comment]
Potentially useful, the following is the shortest query string that I can make for which this reproduces:

```sparql
ask { [<>?o]. }
```

The anonymous node notation is not necessary, I only use it for brevity.  The following also reproduces:

```sparql
ask { ?s<>?o. }
```

**Comment by maxdebayser** [comment]
Hi Everyone, I've submitted a PR for this issue that appears to solve the query parsing problems reported in this issue, as well as some of my own queries. All pre-existing unit tests continue running correctly. 

Actually I wasn't able to reproduce the same parsing error with @wouterbeek 's queries, in both form, with or without my PR I get:
```
SPARQL.js/lib/SparqlParser.js:867
      throw new Error('Cannot resolve relative IRI ' + iri + ' because no base IRI was set.');
      ^

Error: Cannot resolve relative IRI  because no base IRI was set.
    at resolveIRI (SPARQL.js/lib/SparqlParser.js:867:13)
    at Object.anonymous (SPARQL.js/lib/SparqlParser.js:623:35)
    at Parser.parse (SPARQL.js/lib/SparqlParser.js:776:36)
    at Parser.parser.parse (SPARQL.js/sparql.js:31:37)
    at ReadStream.<anonymous> (SPARQL.js/bin/sparql-to-json:25:65)
    at ReadStream.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

**Comment by LaurensRietveld** [comment]
That's good to hear, thanks! The query of Wouter indeed seems to be unrelated (and not a bug)

**Comment by danielbeeke** [comment]
As discussed with @rubensworks, I will work on this issue via the Comunica Association.

**Comment by rubensworks** [comment]
@danielbeeke I see you added the first query mentioned in this issue as unit test in #146. Do you know if the other two queries mentioned in the issue also work now?

**Comment by danielbeeke** [comment]
I don't know.
I can add these also as regression tests, would that be good?

**Comment by rubensworks** [comment]
Sounds good to me!

**Comment by rubensworks** [comment]
@LaurensRietveld Can you confirm that you consider this issue resolved as well?

**Comment by LaurensRietveld** [comment]
@rubensworks Looks good, thanks!
